version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Lint Check
          command: yarn lint
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

workflows:
  build-deploy:
    jobs:
      - lint
